### ISSUE TITLE
Highlighted table row not always visible

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-rem-v3#23]
- Aurelia table to move highlighted row to top

**Comment by tomasholderness** [comment]
@mgvarley - I know you mentioned this to me, but would be great to get your advice for 5 minutes next chance we get to chat.

**Comment by mgvarley** [comment]
Hi Tom - I think the issue is not aurelia-table but the way in which we are using it.  aurelia-table supports pagination however we are not using this currently and instead just have one long table wrapped in a scrolling div.  So I think there are two possible solutions:


1) Use a fixed size table (e.g. 10 rows per page), enable pagination and get rid of the scrolling div in which case the auerlia-table API will return the page of the required area and you can navigate to this programmatically https://tochoromero.github.io/aurelia-table/#pagination



2) Include some kind of anchor reference for each row in the table based on its unique id and then scroll to this programatically on select, there is a post on this here http://stackoverflow.com/questions/10634898/how-can-i-scroll-programmatically-a-div-with-its-own-scrollbars



If you need any help just let me know.


Thanks,


Mark




>

**Comment by tomasholderness** [comment]
Hi @mgvarley - unfortunately because the table (and resulting rows/unique div IDs) are generated programmatically by Aurelia table plugin, they don't exist in time to respond to methods (e.g. offset()). 

Another race condition! Dynamically updated content is tough within Aurelia...will have to keep thinking about this one.
